language: node_js
node_js:
- 5.4.0
branches:
  only:
  - master
before_install:
- export TZ=Asia/Shanghai
- openssl aes-256-cbc -K $encrypted_06b4f6622683_key -iv $encrypted_06b4f6622683_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- npm install -g hexo
before_script:
- git config --global user.name 'Sabrina Luo'
- git config --global user.email 'luohaojing@gmail.com'
- git clone --depth=1 git@github.com:sabrinaluo/hexo-theme-normcore.git themes/normcore
- git clone git@github.com:sabrinaluo/blog.git -b gh-pages --single-branch .deploy_git
script:
- hexo generate
after_success:
- hexo d
- openssl aes-256-cbc -K $encrypted_d940846f0dc7_key -iv $encrypted_d940846f0dc7_iv -in .travis/config.json.enc -out .travis/config.json -d
- node app
